// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpfstun

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadStuntest returns the embedded CollectionSpec for stuntest.
func loadStuntest() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_StuntestBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load stuntest: %w", err)
	}

	return spec, err
}

// loadStuntestObjects loads stuntest and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*stuntestObjects
//	*stuntestPrograms
//	*stuntestMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadStuntestObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadStuntest()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// stuntestSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stuntestSpecs struct {
	stuntestProgramSpecs
	stuntestMapSpecs
	stuntestVariableSpecs
}

// stuntestProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stuntestProgramSpecs struct {
}

// stuntestMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stuntestMapSpecs struct {
}

// stuntestVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stuntestVariableSpecs struct {
}

// stuntestObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadStuntestObjects or ebpf.CollectionSpec.LoadAndAssign.
type stuntestObjects struct {
	stuntestPrograms
	stuntestMaps
	stuntestVariables
}

func (o *stuntestObjects) Close() error {
	return _StuntestClose(
		&o.stuntestPrograms,
		&o.stuntestMaps,
	)
}

// stuntestMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadStuntestObjects or ebpf.CollectionSpec.LoadAndAssign.
type stuntestMaps struct {
}

func (m *stuntestMaps) Close() error {
	return _StuntestClose()
}

// stuntestVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadStuntestObjects or ebpf.CollectionSpec.LoadAndAssign.
type stuntestVariables struct {
}

// stuntestPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadStuntestObjects or ebpf.CollectionSpec.LoadAndAssign.
type stuntestPrograms struct {
}

func (p *stuntestPrograms) Close() error {
	return _StuntestClose()
}

func _StuntestClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed stuntest_bpfel.o
var _StuntestBytes []byte
