// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpfstun

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadStun returns the embedded CollectionSpec for stun.
func loadStun() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_StunBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load stun: %w", err)
	}

	return spec, err
}

// loadStunObjects loads stun and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*stunObjects
//	*stunPrograms
//	*stunMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadStunObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadStun()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// stunSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stunSpecs struct {
	stunProgramSpecs
	stunMapSpecs
	stunVariableSpecs
}

// stunProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stunProgramSpecs struct {
}

// stunMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stunMapSpecs struct {
}

// stunVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stunVariableSpecs struct {
}

// stunObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadStunObjects or ebpf.CollectionSpec.LoadAndAssign.
type stunObjects struct {
	stunPrograms
	stunMaps
	stunVariables
}

func (o *stunObjects) Close() error {
	return _StunClose(
		&o.stunPrograms,
		&o.stunMaps,
	)
}

// stunMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadStunObjects or ebpf.CollectionSpec.LoadAndAssign.
type stunMaps struct {
}

func (m *stunMaps) Close() error {
	return _StunClose()
}

// stunVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadStunObjects or ebpf.CollectionSpec.LoadAndAssign.
type stunVariables struct {
}

// stunPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadStunObjects or ebpf.CollectionSpec.LoadAndAssign.
type stunPrograms struct {
}

func (p *stunPrograms) Close() error {
	return _StunClose()
}

func _StunClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed stun_bpfel.o
var _StunBytes []byte
